### ISSUE TITLE
Find Substitution for AP22811, as it is FAULTY

### ISSUE THREAD

**Issue by Seas0** [greatscottgadgets/luna#171] opened 2022-06-30 15:42 UTC
The AP22811 have been marked as NOT RECOMMENDED FOR NEW DESIGN by Diodes lately, shall we consider use its successor, AP22818, as USB power switch at U1, U12, U13?
_Edit: both of them are ***NOT*** suitable for luna's design, see my latter comment._

**Comment by mossmann** [comment] 2022-06-30 17:17
Yes, AP22818AKEWT-7 looks like the drop-in replacement for AP22811AW5-7 which we have specified.  AP22811AW5-7 is still expected to ship, so I don't think we need to make a change urgently. We already have AP22804AW5-7 and AP22814AW5-7 designated as acceptable substitutes.

I think we should update the part number in the schematic to AP22818AKEWT-7 and add AP22811AW5-7 to the list of substitutes.

**Comment by Seas0** [comment] 2022-07-04 11:05
Well, after some careful examination, it seems the originally used DC switch, AP22811, and the candidate one, AP22818, is ***FAULTY*** in current [[design](https://github.com/greatscottgadgets/luna/blob/main/hardware/rev0/power_supplies.sch)](https://github.com/greatscottgadgets/luna/blob/main/hardware/rev0/power_supplies.sch).
![DC switch design of Luna](https://user-images.githubusercontent.com/30485844/177138460-ed6e0802-763f-4c38-9069-6b5b7e38f5dc.png)

Currently Luna's design assumed these DC switches should maintain the OUT port at High-Z when not enabled, either disable by the pull-down resistor or by FPGA.

But my self-built Luna's DC switches, U1 and U13, were getting ~100 Celsius after plugging in power supply to the target USB type-C port with about 2 watts drew from the power supply, indicating a huge current go through them, so I looked through the [[datasheet](https://www.diodes.com/assets/Datasheets/products_inactive_data/AP22811.pdf)](https://www.diodes.com/assets/Datasheets/products_inactive_data/AP22811.pdf) of AP22811 and found this:

> Discharge Function
> The discharge function of the device is active when enable is disabled or de-asserted. The discharge function with the N-MOS power switch
> implementation is activated and offers a resistive discharge path for the external storage capacitor. This is designed for discharging any residue of
> the output voltage when either no external output resistance or load resistance is present at the output.

![Diagram of AP22811](https://user-images.githubusercontent.com/30485844/177137724-1c40fd77-d1d3-4943-8bba-ac8e94937ad9.png)
![Output resistance of AP22811 when in discharge mode](https://user-images.githubusercontent.com/30485844/177137929-4109704c-fef9-4090-9c2e-c11406c57029.png)

The [[datasheet](https://www.diodes.com/assets/Datasheets/AP22816_17_18.pdf)](https://www.diodes.com/assets/Datasheets/AP22816_17_18.pdf) of AP22818 describe almost the same thing so I'd only provide a link to it for reference.

As cited in their datasheet, they both have the "Fast Discharge" functionality activated in the absence of EN signal, which is actually shorting OUT and GND with a MOSFET and/or a resistor, explained the weird overheating problem as current could flow back to the OUT port of a disabled DC switch and directly drive to ground, easily heating up the DC switch and wasting power of the USB Bus.

**Comment by mossmann** [comment] 2022-07-04 21:56
Nice find! I think you are right that the output discharge function is not ideal for our application, although I don't know that I would say that it is faulty or that it explains the U1/U13 failure you observed.

I measure discharge current at 35 to 40 mA which agrees pretty closely with the discharge resistance of 90 to 130 ohms specified in the data sheet. This is wasteful, but I don't know that it is a big problem.

If you find a more ideal part, I'd love to see it. Otherwise we could decide to accept the discharge current or we could place diodes on the outputs (which would reduce the voltage by the diode drop).

**Comment by mossmann** [comment] 2022-07-04 22:01
AP22818 has a discharge resistance of 140 to 200 ohms which is slightly less wasteful.

**Comment by martinling** [comment] 2022-07-06 12:05
Torex [XC8107](https://www.torexsemi.com/file/xc8107/XC8107.pdf) and [XC8108](https://www.torexsemi.com/file/xc8108/XC8108.pdf) are amongst the few alternatives without load discharge that currently have some stock availability. The XC8108 has the added feature that the current limit is configurable with a resistor.

**Comment by mossmann** [comment] 2022-07-18 21:03
My best guess is that the failure you observed was caused by VOUT overvoltage when VIN was at 0 V. Because of this as well as limitations of reverse current protection, we've been looking into various options and are likely to go with a FET-based solution rather than using integrated load switches.

**Comment by straithe** [comment] 2022-12-08 07:25
I'm closing this issue as there hasn't been any additional conversation in quite a while. Thanks all!

**Comment by mossmann** [comment] 2022-12-08 12:32
I'm reopening this because I'm still working on it.

**Comment by mossmann** [comment] 2023-01-11 11:17
I went with AP2171 on r0.5 to address the initial component lifecycle concern and self-discharge. The overvoltage issue I later identified will be addressed in r0.6.

**Closed by mossmann** 2023-01-11 11:17 UTC
Labels: bug, hardware
